# Automagic Multi-Language Static Analysis on Commit, before Push.
# pip install pre-commit pre-commit-hooks  # http://pre-commit.com
# Use in Continuous Integration,or Force Run,use: pre-commit run --all-files
# Auto-Update all hooks: pre-commit autoupdate
# Also run all hooks on Push: pre-commit install --hook-type pre-push


-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1  # master
    stages: [commit, push]  # When to run.
    hooks:
    -   id: end-of-file-fixer        # Check that Text files ends with new line.
    -   id: trailing-whitespace      # Check for empty trailing white spaces.
    -   id: check-added-large-files  # Check for Text files > 500 Kilobytes.
    -   id: check-byte-order-marker  # Check for BOM byte-order marker on files.
    -   id: check-case-conflict      # Check conflicts for case-insensitive FS.
    -   id: check-docstring-first    # Check for DocStrings placement (if any).
    -   id: check-merge-conflict     # Check for committing Unmerged files.
    -   id: check-symlinks           # Check for SymLinks pointing nowhere.
    -   id: debug-statements         # Check for pdb/ipdb breakpoints in code.
    -   id: fix-encoding-pragma      # Add # -*- coding: utf-8 -*- to .py files.
    -   id: requirements-txt-fixer   # Alphabetically sorts requirements.txt
    -   id: check-ast                # Check for Invalid Broken Python code.
    -   id: detect-private-key       # Check for committing Private Keys.
    -   id: forbid-new-submodules    # Prevent addition of new Git SubModules.
    -   id: check-executables-have-shebangs  # Check if executable have SheBang.
    -   id: check-json               # Check JSON files are valid (if any).
    -   id: check-yaml               # Check YAML files are valid (if any).
    -   id: check-xml                # Check XML files are valid (if any).
#   -   id: flake8                   # Lint all Python files using Flake8.
