language: python

python:
  - 3.5
  - 3.6
  - nightly
  - pypy3


before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"


install:
  - pip install --upgrade pytest pylama isort --quiet
  - pip install .


before_script: rm --recursive --force --verbose *.py[cod]


script:
  - pytest tests/
  - pylama --linters "pep8,isort,pyflakes,pycodestyle" anglerfish/*.py


notifications:
  email:
    recipients: juancarlospaco@gmail.com
    on_success: change
    on_failure: always


cache:
  apt: true
  pip: true
